imports:
    - { resource: datasource.yml }
    - { resource: modules.yml }

templating:
    engines: ["php", "smarty", "twig"]
    globals:
        - ga_tracking: "UA-XXXXX-X"

monolog:
    handlers:
        main:
            type:  stream
            path:  %app.logs_dir%/%app.environment%.log
            level: debug