imports:
    - { resource: datasource.yml }
    - { resource: modules.yml }

framework:
    templating:
        engines: ["php", "smarty", "twig"]
        globals:
            - ga_tracking: "UA-XXXXX-X"

    skeleton_module:
        path: './utils/skeleton_module'

monolog:
    handlers:
        main:
            type:  stream
            path:  %app.logs_dir%/%app.environment%.log
            level: debug