imports:
    - { resource: datasource.yml }

modules:
    active_modules:
    - Framework
    - Application
    - PPI\BowerModule
    - PPI\SmartyModule
    - PPI\TwigModule
    - PPI\TwitterBootstrapModule
    module_listener_options:
        module_paths: ['./modules', './vendor']

framework:
    templating:
        engines: ["php"]

    skeleton_module:
        path: './utils/skeleton_module'